Allow users to download data from the website for each country and institution
The-Academic-Observatory/coki-oa-web pull request #56
Opened 2022-11-29 07:56 UTC by alexmassen-hane

Use fetch to grab the json from Cloudflare KV storage, parse it to CSV and allow it to be downloaded when user clicks the button.

Need to figure out a few kinks with how Cloudflare worker-api gives it's data.

2023-01-04 03:02 UTC, alexmassen-hane commented
Modified the API worker to pull the entity data from KV storage, parse the timeseries and repository data into a CSV like arrays and then zip them up for download when the link of /api/download/[entity.type]/[entity.id] is hit.

The clickable download link for the zip on the COKI OA website for the specific country or institution appears as

![image](https://user-images.githubusercontent.com/104514872/210476319-7d98a8f3-7bce-4fb1-90ce-9e5eaf3f1c7a.png)

2023-01-04 05:45 UTC, alexmassen-hane commented
Instead including the schemas in a separate file in the zip, I have just added a link to the data page for the user to investigate. Also shortened the names of the CSVs. 

![image](https://user-images.githubusercontent.com/104514872/210491858-1e0fb864-43e2-4b1f-ab63-57b002c64c8b.png)

2023-02-07 06:42 UTC, alexmassen-hane commented
Having to force flexsearch to stay at v0.7.2 as there are issues with type definitions in v0.7.3. When the issue has been fixed we can considering upgrading. 

https://github.com/nextapps-de/flexsearch/issues/342
https://github.com/nextapps-de/flexsearch/pull/364

Also added necessary config so it will ignore library files when doing the `yarn types:check` step in the tests, as there are conflicts with the current node and cloudflare type definitions.

2023-02-14 05:32 UTC, jdddog requested changes
Hey Alex, thanks for the PR, it is looking good, the main feedback is about:
* Using the `MetadataLink` object for the download UI functionality.
* Using routing features from itty-router so that you don't have to manually parse route parameters.
* And using a JSON to CSV converter library as it will reduce the amount of code that we have to write for conversion and handle things such as quoting when commas are in strings etc.

2023-02-14 05:32 UTC, jdddog commented on components/details/DownloadDataLink.tsx
> +          a.download = `COKI_data_${entity.entity_type}_${entity.id}.zip`;
Could we call the file Country name + COKI Dataset.zip, e.g "Mali COKI Dataset.zip"?

2023-02-14 05:32 UTC, jdddog commented on components/details/DownloadDataLink.tsx
> +  const dataUrl = `${process.env.COKI_API_URL}/download/${entity.entity_type}/${entity.id}`;
You might need to use `addBuildId` so that when a new version of the app is built, it doesn't fetch stale data from the API.

2023-02-14 09:29 UTC, alexmassen-hane commented on workers-api/src/router.test.ts
> +  expect(results.map(x => lodashGet(x, orderByKey))).toBeSorted({ descending: true });
Looks like my Prettier VS Code extension updated and was using something else. I've forced it to use the one in node_modules. I will change it back in the next commit.

2023-02-14 09:33 UTC, alexmassen-hane commented on workers-api/package.json
> +    "jszip": "^3.10.1",
Looks like this package is.
https://www.apache.org/licenses/GPL-compatibility.html

I will keep this in mind, thanks.

2023-03-06 22:07 UTC, jdddog requested changes
Hey Alex, the changes look great. It looks like Typescript support is coming for the json2csv package, so we can update it when that is released.

I've left a few smaller comments. I also need to do a few things, including making the icon, checking about the authors and license of the jszip library.

2023-04-03 01:41 UTC, merged